### PR TITLE
Add support for Serene Seasons

### PR DESCRIPTION
**Pull request by MarioSMB**
Allows corn crops to be grown seasonally with the Serene Seasons mod

### CODE REVIEW

**Comment by 0999312** [comment]
Thank you!

**Comment by Sinuisan** [comment]
Any chance this could be integrated into the 1.16.5 branch? I'm not seeing an updated file on Curse for 1.16 :(
Or would you prefer to leave it and a datapack can just be linked?

**Comment by MarioSMB** [comment]
It should be fairly trivial to perform a merge commit from main to the 1.16.5 branch, so I'll leave that to you.  
In the meantime, here's a datapack that should work in that version: [seasonal_corn.zip](https://github.com/0999312/Corn-Delight/files/8211361/seasonal_corn.zip)
Enjoy!

**Comment by 0999312** [comment]
Well, 1.16.5 Updated to CF.

**Comment by Sinuisan** [comment]
> Well, 1.16.5 Updated to CF.

Im confused - CF?

**Comment by MarioSMB** [comment]
CF is CurseForge, which means the update should be live. Thank you for the hasty progress!

**Pull request merged**
